### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by pdxwolfy** [mark-hahn/tab-smart-sort#10]
[Enter steps to reproduce below:]
1. Set up clean instance of Atom with no additional packages
2. Install tab-smart-sort with default settings
3. Open atom
4. Open some files
5. Split the window into at least two panes
6. Drag and drop any open file into the new pane

Basically, this package renders drag and drop in panes inoperable.

```
**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [tab-smart-sort](https://github.com/mark-hahn/tab-smart-sort) package, v0.1.4


### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```

At /Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:387:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:487:20)
    at Pane.addItem (/Users/vanilla/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:67:19)
    at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:612:19)
    at atom-tabs.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:728:20)
    at atom-tabs.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:605:23)

```

### Commands

```

```
 -1:47.9.0 settings-view:open (atom-text-editor.editor.is-focused)
 -1:35.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 -1:12.3.0 application:open (atom-text-editor.editor.is-focused)
```

  2x -0:56.6.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -0:43.4.0 application:open (atom-text-editor.editor.is-focused)
     -0:12 pane:split-right (atom-text-editor.editor.is-focused)

``````

### Config

```json
{}
``````
### Installed Packages

``` coffee
# User
tab-smart-sort, v0.1.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:387:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:487:20)
    at Pane.addItem (/Users/vanilla/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:67:19)
    at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:612:19)
    at atom-tabs.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:728:20)
    at atom-tabs.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:605:23)
The error was thrown from the tab-smart-sort package. This issue has already been reported.
View Issue

```
```

**Comment by pdxwolfy** [comment]
This is similar - maybe identical - to a closed issue, but there is no way to reopen that, and at least one subsequent report since the closure has been ignored. Thank you for your attention.

**Comment by opensourceportfolio** [comment]
I keep running into this issue everytime I move one tab to another panel

**Comment by redfellow** [comment]
Same here, splitting tab requires a full reload after due this error.

**Comment by jspiro** [comment]
Unable to reproduce. Pull the latest and try it.

**Comment by pdxwolfy** [comment]
The update appears to fix the issue. Thank you.
