### ISSUE TITLE
Uncaught TypeError: Cannot set property 'index' of undefined

### ISSUE THREAD

**Issue by kravlost** [mark-hahn/tab-smart-sort#16]
[Enter steps to reproduce:]

1. Right click on Project Viewer
2. Select Create new Project

**Atom**: 1.19.0-beta2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tab-smart-sort](https://github.com/jspiro/tab-smart-sort) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot set property 'index' of undefined

```
At C:\Users\steve\.atom\packages\tab-smart-sort\lib\tab-smart-sort.coffee:69

TypeError: Cannot set property 'index' of undefined
    at Pane.addItem (/packages/tab-smart-sort/lib/tab-smart-sort.coffee:69:3)
    at /packages/project-viewer/src/main-view.js:101:14)
    at Object._createNewProject (/packages/project-viewer/src/main.js:634:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:45.5.0 settings-view:open (div.tool-panel.tree-view)
  2x -4:36 core:confirm (input.hidden-input)
     -3:53.2.0 core:backspace (input.hidden-input)
     -3:52.9.0 core:confirm (input.hidden-input)
     -1:17.7.0 core:move-left (input.hidden-input)
     -1:16.6.0 core:delete (input.hidden-input)
     -0:16.4.0 project-viewer:createNewProject (ul.background-message.centered)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.3 
autocomplete-clang 0.11.3 
docblockr 0.10.5 
file-icons 2.1.8 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
keybinding-cheatsheet 0.1.1 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
multi-cursor 2.1.5 
open-recent 5.0.0 
project-viewer 1.2.0 
simple-drag-drop-text 0.3.4 
symbols-tree-view 0.14.0 
tab-smart-sort 0.3.0 
todo-show 1.11.0 
```

**Comment by UnConundrum** [comment]
Any progress on this?   I'm having the same problem.

**Comment by projectrigger** [comment]
I have the same problem. Is there a solution for this?
